model:
  dim:                   1024
  depth:                 16
  early_depth:           2
  heads:                 16
  pool_every_k_blocks: 4
  cls_dropout_rate: 0.05
  cls_pool_alpha_requires_grad: true
  cls_pool_alpha_init: 1.0
  adaptive_pool_temperature: 1.0
  policy_head_conv_dim: 512
  policy_head_mlp_hidden_dim: 1024
  value_head_dropout_rate: 0.3
  num_policy_planes: 73
  drop_path: 0.1
  # SmolGen parameters
  smolgen_start_layer: 4
  smolgen_latent_dim: 512
  smolgen_dropout: 0.1
  # Value head parameters
  value_spatial_compress_dim: 48
  value_head_mlp_dims: [1024, 256]
  moves_left_spatial_compress_dim: 12
  moves_left_head_mlp_dims: [512, 128]
  # Hybrid patch embedding parameters
  patch_resblock_hidden: 64
  patch_global_proj_dim: 32
  patch_embed_dropout: 0.1

loss_weights:
  policy:           1.0
  value:            1.6
  moves_left:       0.15
  auxiliary_value:  0.2   # early‐group WDL head
  material:         0.1

optimiser:
  type:             adamw
  lr:               1.5e-4
  weight_decay:     1e-2
  betas:            [0.9, 0.95]
  sched:            cosine
  warmup_steps:     1500

dataset:
  data_dir:     data/train/lc0
  test_data_dir:    data/test/lc0    # files directly in test/ not in subdirectories
  batch_size:       128
  test_batch_size:  256
  grad_accum:       4
  num_workers:      4
  flips:            true
  type:             tensor
  tensor_glob_pattern: '**/*.npz'

runtime:
  device:           cuda
  precision:        fp16
  max_steps:        4200000
  log_every:        500
  ckpt_every:       50000
  val_every:        200000
  checkpoint_format: safetensors
  gradient_clip_norm: 1.0   # global‐norm
  gradient_clip_value: 10.0
  gradient_checkpointing: true
  compile_model: false # Can be enabled for ~10% speedup, but uses more memory

logging:
  output_dir:       ./runs/v2/large
  tensorboard:      true
  matplotlib:       true
  wandb:            false

rolling_metrics:
  window_size:      1000