model:
  dim:                   64         # 2 heads × 32d - minimal for testing
  depth:                 3
  early_depth:           1
  heads:                 2
  pool_every_k_blocks:   null       # No pooling for minimal test
  cls_dropout_rate:      0.0
  cls_pool_alpha_requires_grad: true
  cls_pool_alpha_init:   1.0
  adaptive_pool_temperature: null
  policy_head_conv_dim:  32
  policy_head_mlp_hidden_dim: 64
  value_head_dropout_rate: 0.0
  num_policy_planes:     73
  drop_path:             0.0
  # SmolGen parameters (shared module)
  smolgen_start_layer:   1
  smolgen_latent_dim:    32
  smolgen_dropout:       0.0
  # Value head parameters
  value_spatial_compress_dim: 10     # Minimal compression
  value_head_mlp_dims:   [64]
  moves_left_spatial_compress_dim: 4
  moves_left_head_mlp_dims: [32]
  # Hybrid patch embedding parameters
  patch_resblock_hidden: 16
  patch_global_proj_dim: 4
  patch_embed_dropout:   0.0

loss_weights:
  policy:           1.0
  value:            1.6
  moves_left:       0.2
  auxiliary_value:  0.2   # early‐group WDL head
  material:         0.03

optimiser:
  type:             adamw
  lr:               1e-3
  weight_decay:     1e-2
  betas:            [0.9, 0.95]
  sched:            cosine
  warmup_steps:     100

dataset:
  data_dir:     data/train/lc0
  test_data_dir:    data/test/lc0    # files directly in test/ not in subdirectories
  batch_size:       1024
  test_batch_size:  2048
  grad_accum:       1
  num_workers:      4
  type:             tensor
  tensor_glob_pattern: '*.npz'

runtime:
  device:           cuda
  precision:        fp16
  max_steps:        1000
  log_every:        50
  ckpt_every:       500
  val_every:        250
  checkpoint_format: safetensors
  gradient_clip_norm: 0.5   # global‐norm clipping
  gradient_clip_value: 5.0  # value clipping for stability
  gradient_checkpointing: false
  compile_model: false # Disable for testing to avoid compilation overhead
  compile_with_cudagraphs: false

logging:
  output_dir:       ./runs/v3/test
  tensorboard:      true
  matplotlib:       true
  wandb:            false

rolling_metrics:
  window_size:      100