model:
  dim:                   96
  depth:                 6
  early_depth:           2
  heads:                 6
  pool_every_k_blocks: 3
  cls_dropout_rate: 0.05
  cls_pool_alpha_requires_grad: true
  cls_pool_alpha_init: 1.0
  adaptive_pool_temperature: 1.0
  policy_head_conv_dim: 384
  policy_head_mlp_hidden_dim: 384
  value_head_dropout_rate: 0.3
  num_policy_planes: 73
  drop_path: 0.1
  # SmolGen parameters
  smolgen_start_layer: 1
  smolgen_latent_dim: 64
  smolgen_dropout: 0.1
  # Value head parameters
  value_spatial_compress_dim: 24
  value_head_mlp_dims: [128, 64]
  moves_left_spatial_compress_dim: 4
  moves_left_head_mlp_dims: [64, 32]
  # Hybrid patch embedding parameters
  patch_resblock_hidden: 24
  patch_global_proj_dim: 12
  patch_embed_dropout: 0.1

loss_weights:
  policy:           1.0
  value:            1.6
  moves_left:       0.15
  auxiliary_value:  0.2   # early‐group WDL head
  material:         0.1

optimiser:
  type:             adamw
  lr:               1.5e-4
  weight_decay:     1e-2
  betas:            [0.9, 0.95]
  sched:            cosine
  warmup_steps:     1500

dataset:
  data_dir:     data/train/lc0
  test_data_dir:    data/test/lc0    # files directly in test/ not in subdirectories
  batch_size:       1280
  grad_accum:       4
  num_workers:      5
  type:             tensor
  tensor_glob_pattern: '*.npz'

runtime:
  device:           cuda
  precision:        fp16
  max_steps:        1500000
  log_every:        10000
  ckpt_every:       200000
  val_every:        100000
  checkpoint_format: safetensors
  gradient_clip_norm: 0.5   # global‐norm clipping
  gradient_clip_value: 5.0  # value clipping for stability

logging:
  output_dir:       ./runs/v2/tiny
  tensorboard:      true
  matplotlib:       true
  wandb:            false

rolling_metrics:
  window_size:      1000